platform :ios, '7.0'
pod 'Parse', '~> 1.6'
pod 'PayPal-iOS-SDK', '~> 2.8'
pod 'AFNetworking', '~> 2.2'
pod 'DDPageControl', '~> 0.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'WYPopoverController', '~> 0.2.2'